name: Commits Syntax Checker

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, edited, review_requested, synchronize]
  push:
    branches:
      - "main"
  workflow_call:

jobs:
  check:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: webiny/action-conventional-commits@v1.0.3

      - name: Set Badge for Commit Status (Success)
        if: success()
        run: |
          echo "Commit Status: ![Commit Message Valid](https://img.shields.io/badge/Commit%20Message-Valid-brightgreen)" > badge.txt
      
      - name: Set Badge for Commit Status (Failure)
        if: failure()
        run: |
          echo "Commit Status: ![Commit Message Needs Fixing](https://img.shields.io/badge/Commit%20Message-Needs%20Fixing-red)" > badge.txt

      - name: Post Badge in PR comment
        if: always()
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Commit Status:
            ![Badge](${{ env.badge_url }})