name: Run Tests and Post Coverage

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: uvlhub_root_password
          MYSQL_DATABASE: uvlhubdb_test
          MYSQL_USER: uvlhub_user
          MYSQL_PASSWORD: uvlhub_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Prepare environment
        run: |
          sed -i '/rosemary @ file:\/\/\/app/d' requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests with Coverage and Generate XML Report
        run: |
          pytest --cov=app/modules/ --cov-report=xml:coverage.xml --ignore-glob='*selenium*'

      - name: Parse Coverage Report and Comment on PR
        uses: peter-evans/create-or-update-comment@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.pull_request.number }}
          body: |
            ## Test Coverage Report
            ```text
            $(python -c '
            import xml.etree.ElementTree as ET
            tree = ET.parse("coverage.xml")
            root = tree.getroot()
            for elem in root.iter("coverage"):
                line_rate = elem.get("line-rate")
                branch_rate = elem.get("branch-rate")
                print(f"Line Coverage: {float(line_rate) * 100:.2f}%")
                print(f"Branch Coverage: {float(branch_rate) * 100:.2f}%")
            ')
            ```
